# Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.data.rest.detection-strategy=annotated
spring.main.allow-circular-references=true
# Security OAuth2 Client Registration
spring.security.oauth2.client.registration.pingone.client-id=${PINGONE_CLIENT_ID}
spring.security.oauth2.client.registration.pingone.client-secret=${PINGONE_CLIENT_SECRET}
spring.security.oauth2.client.registration.pingone.scope=email,openid,phone
spring.security.oauth2.client.registration.pingone.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.pingone.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.pingone.client-name=Ping One
spring.security.oauth2.client.provider.pingone.issuer-uri=https://auth.pingone.com/21620bf7-6daf-4fd6-a951-ae0f9b1bd7af/as
spring.security.oauth2.client.provider.pingone.user-name-attribute=username
# Server configuration
server.servlet.context-path=/app
server.port=8080
# Logging configuration
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security.web=debug
logging.level.org.springframework.security.saml=DEBUG
logging.level.org.opensaml.xmlsec=DEBUG
logging.org.opensaml.xmlsec=DEBUG